sudo: required
services:
  - docker

before_install:
  - docker build -t ewallace/travci -f Dockerfile.dev .


script:
  - docker run -e CI=true ewallace/travci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-814285234391"
  bucket_path: "app-travisci"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
